# примеры API-запросов

# получение объявлений
GET http://127.0.0.1:8000/advertisement/
Content-Type: application/json

###
# создание объявления
POST http://127.0.0.1:8000/advertisement/
Content-Type: application/json
Authorization: Token 4072c5298506d563f236ba5b9b4397d707d6a41d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/advertisement/3/
Content-Type: application/json
Authorization: Token 4072c5298506d563f236ba5b9b4397d707d6a41d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://127.0.0.1:8000/advertisement/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET http://127.0.0.1:8000/advertisement/?created_at_after=2026-07-10
Content-Type: application/json

###
