# примеры API-запросов

# получение объявлений
GET http://127.0.0.1:8000/api/advertisements/
Content-Type: application/json

###
# создание объявления
POST http://127.0.0.1:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 34b22029941f030fe932f3a35714d6679c516ea4

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/api/advertisements/4/
Content-Type: application/json
Authorization: Token 34b22029941f030fe932f3a35714d6679c516ea4

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://127.0.0.1:8000/api/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET http://127.0.0.1:8000/api/advertisements/?created_after=2026-07-30
Content-Type: application/json

###
